# Generated by Django 5.2.1 on 2025-05-27 19:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(verbose_name='Режим работы')),
                ('payment_info', models.TextField(verbose_name='Информация по оплате')),
                ('contact_image', models.ImageField(upload_to='contacts/', verbose_name='Изображение контактов')),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Дополнительное изображение оплаты')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страница контактов',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100, verbose_name='Заголовок баннера')),
                ('banner_subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок баннера')),
                ('about_title', models.CharField(max_length=100, verbose_name="Заголовок 'О бренде'")),
                ('about_content', ckeditor.fields.RichTextField(verbose_name="Текст 'О бренде'")),
                ('order_title', models.CharField(max_length=100, verbose_name="Заголовок 'Как сделать заказ'")),
                ('gift_title', models.CharField(max_length=100, verbose_name="Заголовок 'Подарочный сертификат'")),
                ('gift_content', ckeditor.fields.RichTextField(verbose_name="Текст 'Подарочный сертификат'")),
                ('banner_image', models.ImageField(upload_to='homepage/', verbose_name='Баннер')),
                ('image1', models.ImageField(upload_to='homepage/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(upload_to='homepage/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(upload_to='homepage/', verbose_name='Изображение 3')),
                ('order_image', models.ImageField(upload_to='homepage/', verbose_name='Изображение процесса заказа')),
                ('gift_image', models.ImageField(upload_to='homepage/', verbose_name='Изображение сертификата')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product', verbose_name='Товар')),
            ],
        ),
    ]
